# Generated by Django 5.0.4 on 2024-04-25 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_coupon_end_date_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 8, 4, 6, 336913, tzinfo=datetime.timezone.utc)),
        ),
    ]
